name: ConvexHullCriterion
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.6.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - babel=2.10.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=5.0.0
  - brotlipy=0.7.0
  - ca-certificates=2022.5.18.1
  - certifi=2022.5.18.1
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - colorama=0.4.4
  - cryptography=37.0.2
  - debugpy=1.6.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - flit-core=3.7.1
  - hdbscan=0.8.27
  - idna=3.3
  - importlib-metadata=4.11.4
  - importlib_metadata=4.11.4
  - importlib_resources=5.7.1
  - intel-openmp=2022.1.0
  - ipykernel=6.13.0
  - ipython=8.3.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.0
  - json5=0.9.5
  - jsonschema=4.5.1
  - jupyter_client=7.3.1
  - jupyter_core=4.10.0
  - jupyter_server=1.17.0
  - jupyterlab=3.1.1
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.14.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - liblapack=3.9.0
  - libsodium=1.0.18
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - mkl=2022.0.0
  - msys2-conda-epoch=20160418
  - nbclassic=0.3.7
  - nbclient=0.6.3
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbformat=5.4.0
  - nest-asyncio=1.5.5
  - notebook=6.4.11
  - notebook-shim=0.1.0
  - numpy=1.22.4
  - openssl=1.1.1o
  - packaging=21.3
  - pandoc=2.18
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=21.2.2
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.29
  - psutil=5.9.1
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.12.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - python=3.8.10
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.3
  - python_abi=3.8
  - pytz=2022.1
  - pywin32=303
  - pywinpty=0.5.7
  - pyzmq=23.0.0
  - requests=2.27.1
  - scikit-learn=1.1.1
  - scipy=1.8.1
  - send2trash=1.8.0
  - setuptools=61.2.0
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.1
  - sqlite=3.38.3
  - stack_data=0.2.0
  - tbb=2021.5.0
  - terminado=0.9.5
  - threadpoolctl=3.1.0
  - tinycss2=1.1.1
  - tornado=6.1
  - traitlets=5.2.1.post0
  - urllib3=1.26.9
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.3.2
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - zeromq=4.3.4
  - zipp=3.8.0
  - pip:
    - asdf==2.11.1
    - asdf-standard==1.0.2
    - asdf-transform-schemas==0.2.2
    - asteval==0.9.27
    - async-timeout==4.0.2
    - boost-histogram==1.3.1
    - brokenaxes==0.5.0
    - build==0.8.0
    - click==8.1.3
    - colorcet==2.0.6
    - cycler==0.11.0
    - cython==0.29.30
    - deprecated==1.2.13
    - fast-histogram==0.11
    - filelock==3.7.0
    - fonttools==4.33.3
    - future==0.18.2
    - grpcio==1.46.3
    - imageio==2.19.2
    - jmespath==1.0.0
    - kiwisolver==1.4.2
    - llvmlite==0.38.1
    - lmfit==1.0.3
    - locan==0.11.1
    - matplotlib==3.5.2
    - msgpack==1.0.3
    - networkx==2.8.2
    - numba==0.55.2
    - pandas==1.4.2
    - param==1.12.1
    - pep517==0.13.0
    - pillow==9.1.1
    - pip-tools==6.8.0
    - protobuf==3.20.1
    - pyct==0.4.8
    - pywavelets==1.3.0
    - pyyaml==6.0
    - ray==1.8.0
    - redis==4.3.1
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.6
    - scikit-image==0.19.2
    - semantic-version==2.10.0
    - shapely==1.8.2
    - tifffile==2022.5.4
    - tomli==2.0.1
    - tqdm==4.64.0
    - uncertainties==3.1.6
    - wrapt==1.14.1
